DATASET:
  DATASET_DIR: './dataset'
  TRAINING_DIR: './dataset/train'
  TESTING_DIR: './dataset/val'


  TRAINING_DATASET_LEN: 50_000 # Change this to 100k may get better performance
  TESTING_DATASET_LEN: 1_000


  CAPTCHA:
    FONT_DIR: './fonts/font1.ttf'
    IMG_HEIGHT: 224
    IMG_WIDTH: 224

    CLASS_NUM:  63
    CHAR_LEN: 5


SOLVER:
  LR: 5.0e-5
  BATCH_SIZE: 32
  EPOCH: 10_000



LOGGER:
  CHECKPOINT_DIR: './checkpoint'
  LOG_DIR: './logs'


TRAINER:
  PRECISION: '16-mixed'

