DATASET:
  DATASET_DIR: './dataset'
  TRAINING_DIR: './dataset/train'
  TESTING_DIR: './dataset/val'


  TRAINING_DATASET_LEN: 300_000 # Change this to 100k may get better performance
  TESTING_DATASET_LEN: 3


  CAPTCHA:
    FONT_DIR: './fonts/font1.ttf'
    IMG_HEIGHT: 224
    IMG_WIDTH: 224

    CLASS_NUM: 63
    CHAR_LEN: 5


SOLVER:
  # LR: 5.0e-4
  LR: 8.0e-4
  BATCH_SIZE: 
  EPOCH: 20


LOGGER:
  CHECKPOINT_DIR: './checkpoint'
  LOG_DIR: './logs'

TRAINER:
  PRECISION: '16-mixed'









